import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";

const Home: NextPage = () => {

  const { data: session, status } = useSession();

  if (status == "loading") {
    return (
      <main className="flex h-screen">
        <div className="m-auto">
          Loading...
        </div>
      </main>
    )
  }

  return (
    <>
      <Head>
        <title>Guestbook by Nathan Baylon</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex h-screen flex-col p-4">
        <div className="mb-16">
          <h1 className="text-4xl text-gray-200 text-center">
            Guestbook
          </h1>
        </div>

        <div className="text-center">
          {session ? (
            <div>
              <div>
                Hello, {session.user?.name}
              </div>

              <div className="mb-12">
                Email is {session.user?.email}
              </div>

              <button onClick={() => signOut()} className="bg-blue-500 hover:bg-blue-700 py-1 px-2 rounded">
                Logout
              </button>
            </div>
          ) : (
            <div>
              <button onClick={() => signIn('discord')} className="bg-blue-500 hover:bg-blue-700 py-1 px-2 rounded">
                Sign in with Discord
              </button>
            </div>
          )}
        </div>
      </main>
    </>
  );
};

export default Home;
